name: build
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/integration'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java -cp java SortingMadness
